### ISSUE TITLE
No "0 Min" and No "Sound" Alerts on FA Notifier

### ISSUE THREAD

**Issue by jkun-stargus-sc1gus-2020s** [DASPRiD/furaffinity-notifier#1]
(READ, COMMENT AND DO NOT IGNORE MY MESSAGE, PLEASE. I DARE YA. -.-)
First i've installed FA Notifier (probably regular or the + version) on my Firefox, then went to my Add-ons page, then go to options, and there's no sound alerts and no update interval saying "0 Min" (well, i recommend "moments ago" instead of seconds and minutes ago because i'm tired of waiting) on there. :(

I like my desktop notifications on websites that have notes and PMs having sound alerts and things saying "moments ago" or "just now" for PMs and Messages so that i can talk to people online with notes and PMs with no Discord (because i dislike Discord for my life).

If not, i'm going to quit deviantArt, Inkbunny, FurAffinity and other sites that have notes and PMs.

Also, help me out here with my desktop notifications for FA (Well i have a FA account for an important reason being) and please update and add important things on there like "0 Min" for update interval and sound alerts. (If not, i'm going to be in a "No talking to people" hell on FA.

Anyways,
Thank you for reading and not ignoring my message! ;D

**Comment by DASPRiD** [comment]
An update interval of 0 minutes makes no sense. A really short interval of just a few seconds would also pretty much DOS FA if everyone would use that. If you want real-time notifications when new messages arrive, you should rather ask Furaffinity to add web push-notifications one can subscribe to.

**Comment by jkun-stargus-sc1gus-2020s** [comment]
> An update interval of 0 minutes makes no sense.

That's a lie DASPRiD, that's a lie (Not a truth), it's a lie! I need 0 minutes, not 1 minute (1 minute can't be quick and it won't help me wait). I want to be super quick (not slow) on checking messages, like PMs and notes (because i want to talk to people online). I want to hear them, i'm telling you the truth to make a good sense of help with things i need to use.

> A really short interval of just a few seconds would also pretty much DOS FA if everyone would use that.

Well, seconds won't help, i need moments ago that can help. Don't you get it, man? -_-

> If you want real-time notifications when new messages arrive, you should rather ask Furaffinity to add web push-notifications one can subscribe to.

I do, but asking FurAffinity would make the staff won't answer me and my PMs (the guys won't answer and reply people's messages), them not answering me makes no sense to me.
If i want web push-notifications, my browser has to be in private window mode (not regular window mode like public window mode), because allowing notifications and sound won't work in private windows (i'm having issues).

If you nor anybody helping, i'll definitely quit no matter what it takes to have sound alerts and 0 min update interval for my notification add-ons for dA, FA, Inkbunny, pixiv and others.


Besides, life gets hard without moments ago notifications, especially me. If so, i'm outta here. :\

**Comment by Qeteshpony** [comment]
@feruenzerujkun If you want a chat, get a chat system like Discord. FA is not one. And it is clearly not the purpose of this plugin to turn FA into a chat. 
Also if you have no clue about the technical background you shouldn't call @DASPRiD a liar. Unlike you, he clearly knows what he's talking about. 
The things you ask for need to be implemented by FurAffinity. A browser plugin can not do that.

**Comment by jkun-stargus-sc1gus-2020s** [comment]
> If you want a chat, get a chat system like Discord. FA is not one. And it is clearly not the purpose of this plugin to turn FA into a chat.
Also if you have no clue about the technical background you shouldn't call @DASPRiD a liar. Unlike you, he clearly knows what he's talking about.
The things you ask for need to be implemented by FurAffinity. A browser plugin can not do that.

You know what... no, i'm not keeping Discord while my dA account FeruEnzeru is dead and gone because of enslavers. Discord is hellish and parasitic bullcrap because they always spy on chatrooms and other people on there (especially emulation programs for computers) just like 2017 where Kaze Emanuar, deviantArt and its good people became brainwashed zombies and slaves by Discord and their five queen bitch mothers (Discord is evil, corrupt and enslavers to deviantArt because there's women on dA from the US, and dA people along with Inkbunny and pixiv people say words that are lies to me). If you think DASPRiD's a liar and an asshole about "No 0 min update intervals" and "No sound alerts" on my favorite sites, that's none of your business. >:p

all this Discord crap can go to hell, Notes and PMs unless automatic desktop notification plugins and add-ons for them are my life's protection against lies and corruption and they are better than that crap (Discord are online brain enslaving and parasitic aliens taking over online humans, PM sites and the entire planet Earth!). Bye-bye now! (i'm not gonna lie) ;\

**Comment by Qeteshpony** [comment]
@feruenzerujkun You don't need a browser plugin but a good psychotherapist...
